// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhoSHNwodNdoNCrCzftyEiW22iHa33i8w',
    appId: '1:972604838572:web:5163ae709e1ddc29cf8509',
    messagingSenderId: '972604838572',
    projectId: 'belay-buddy-85d82',
    authDomain: 'belay-buddy-85d82.firebaseapp.com',
    storageBucket: 'belay-buddy-85d82.firebasestorage.app',
    measurementId: 'G-GRLLB0P1B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs2uMgTZOnWhRWQ1maul01vO9gtmtFmec',
    appId: '1:972604838572:android:aa5e20251514ba6bcf8509',
    messagingSenderId: '972604838572',
    projectId: 'belay-buddy-85d82',
    storageBucket: 'belay-buddy-85d82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBduBkWcqxtPfjqMq9I6E2cw_OUAkao6AQ',
    appId: '1:972604838572:ios:49c6b951ffe23578cf8509',
    messagingSenderId: '972604838572',
    projectId: 'belay-buddy-85d82',
    storageBucket: 'belay-buddy-85d82.firebasestorage.app',
    iosBundleId: 'com.example.belayBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBduBkWcqxtPfjqMq9I6E2cw_OUAkao6AQ',
    appId: '1:972604838572:ios:49c6b951ffe23578cf8509',
    messagingSenderId: '972604838572',
    projectId: 'belay-buddy-85d82',
    storageBucket: 'belay-buddy-85d82.firebasestorage.app',
    iosBundleId: 'com.example.belayBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhoSHNwodNdoNCrCzftyEiW22iHa33i8w',
    appId: '1:972604838572:web:8a8e99ea7b772906cf8509',
    messagingSenderId: '972604838572',
    projectId: 'belay-buddy-85d82',
    authDomain: 'belay-buddy-85d82.firebaseapp.com',
    storageBucket: 'belay-buddy-85d82.firebasestorage.app',
    measurementId: 'G-0TSSG369ZW',
  );

}